export enum KeyValueListOptionEnum {
  name = "name",
  wkn = "wkn",
  isin = "isin",
  priceEarningRatio = "priceEarningRatio",
  domicile = "domicile",
  shareSector = "shareSector",
  homepage = "homepage",
  replication = "replication",
  morningstar = "morningstar",
  savingsPlan = "savingsPlan",
  focus = "focus",
  runningCostsPerAnnum = "runningCostsPerAnnum",
  performanceFeePerAnnum = "performanceFeePerAnnum",
  fundCategory = "fundCategory",
  fundTypeFocus = "fundTypeFocus",
  distributionType = "distributionType",
  fundAssets = "fundAssets",
  fundCurrency = "fundCurrency",
}
