export enum PageTypeVolksbankEnum {
  addressesPage = "addresses-page",
  adminDashboardPage = "admin-dashboard-page",
  adminsPage = "admins-page",
  bankDetailsPage = "bank-details-page",
  contactPage = "contact-page",
  contractsPage = "contracts-page",
  dashboardPage = "dashboard-page",
  documentUploadPage = "document-upload-page",
  eCommAccessPage = "e-comm-access-page",
  hpUserPage = "hp-user-page",
  loginPage = "login-page",
  myDocumentsPage = "my-documents-page",
  notFoundPage = "not-found-page",
  notFoundRedirectPage = "not-found-redirect-page",
  reportPage = "report-page",
  settingsPage = "settings-page",
  systemLogsPage = "systemLogs-page",
}
