import { AssetClassEnum } from "@adesso/util-contracts";
import { QuotesInterface } from "@adesso/util-contracts";
import { CompositionModel } from "./composition.model";
import { QuoteModel } from "./quote.model";

export class InstrumentListItemModel implements QuotesInterface {
  name?: string;
  originalName?: string;
  valor?: number;
  isin?: string;
  wkn?: string;
  assetClass?: AssetClassEnum;
  domicile?: string;
  instrumentType?: string;
  changeYearToDatePercent?: number;
  changeYearToDateAbsolute?: number;
  changeOneWeekPercent?: number;
  changeOneMonthPercent?: number;
  changeThreeMonthPercent?: number;
  changeSixMonthPercent?: number;
  changeOneYearPercent?: number;
  yearHigh?: number;
  yearHighDate?: Date;
  yearLow?: number;
  yearLowDate?: Date;
  changeTwoYearsPercent?: number;
  changeThreeYearsPercent?: number;
  threeYearsHigh?: number;
  threeYearsHighDate?: Date;
  threeYearsLow?: number;
  threeYearsLowDate?: Date;
  changeFiveYearsPercent?: number;
  fiveYearsHigh?: number;
  fiveYearsHighDate?: Date;
  fiveYearsLow?: number;
  fiveYearsLowDate?: Date;
  changeTenYearsPercent?: number;
  currencyId?: number;
  currencyCode?: string;
  exchangeId?: number;
  exchangeCode?: string;
  exchangeName?: string;
  dailyHigh?: number;
  dailyHighDate?: Date;
  dailyLow?: number;
  dailyLowDate?: Date;
  volume?: number;
  oneWeekHigh?: number;
  oneWeekHighDate?: Date;
  oneWeekLow?: number;
  oneWeekLowDate?: Date;
  oneMonthHigh?: number;
  oneMonthHighDate?: Date;
  oneMonthLow?: number;
  oneMonthLowDate?: Date;
  threeMonthHigh?: number;
  threeMonthHighDate?: Date;
  threeMonthLow?: number;
  threeMonthLowDate?: Date;
  morningStarRating?: number;
  last?: QuoteModel;
  bid?: QuoteModel;
  ask?: QuoteModel;
  valuation?: QuoteModel;
  nav?: QuoteModel;
  compositions?: CompositionModel[];
}
